# config/cities/all_states.py
# Ciudades principales por estado para scraping de Yelp

STATE_CITIES = {
    "AL": ["Birmingham", "Montgomery", "Huntsville", "Mobile", "Tuscaloosa"],
    "AK": ["Anchorage", "Fairbanks", "Juneau", "Sitka", "Ketchikan"],
    "AZ": ["Phoenix", "Tucson", "Scottsdale", "Tempe", "Mesa", "Chandler", "Gilbert", "Glendale", "Peoria"],
    "AR": ["Little Rock", "Fort Smith", "Fayetteville", "Springdale", "Jonesboro"],
    "CA": ["Los Angeles", "San Francisco", "San Diego", "San Jose", "Sacramento",
            "Fresno", "Oakland", "Long Beach", "Bakersfield", "Anaheim",
            "Beverly Hills", "Pasadena", "Santa Monica", "Irvine", "Riverside"],
    "CO": ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Boulder",
            "Lakewood", "Thornton", "Arvada", "Westminster", "Pueblo"],
    "CT": ["Bridgeport", "New Haven", "Hartford", "Stamford", "Waterbury", "Greenwich"],
    "DE": ["Wilmington", "Dover", "Newark"],
    "DC": ["Washington"],
    "FL": ["Miami", "Orlando", "Tampa", "Jacksonville", "Fort Lauderdale",
            "St. Petersburg", "Hialeah", "Tallahassee", "Boca Raton", "Sarasota",
            "Naples", "Fort Myers", "West Palm Beach", "Gainesville", "Pensacola",
            "Coral Gables", "Aventura", "Doral", "Kendall", "Hollywood"],
    "GA": ["Atlanta", "Augusta", "Columbus", "Macon", "Savannah",
            "Athens", "Sandy Springs", "Roswell", "Alpharetta", "Marietta"],
    "HI": ["Honolulu", "Hilo", "Kailua", "Pearl City", "Wailuku"],
    "ID": ["Boise", "Nampa", "Meridian", "Idaho Falls", "Pocatello"],
    "IL": ["Chicago", "Aurora", "Rockford", "Joliet", "Naperville",
            "Springfield", "Peoria", "Elgin", "Waukegan", "Champaign"],
    "IN": ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel",
            "Fishers", "Hammond", "Muncie", "Lafayette", "Terre Haute"],
    "IA": ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Iowa City"],
    "KS": ["Wichita", "Overland Park", "Kansas City", "Topeka", "Olathe"],
    "KY": ["Louisville", "Lexington", "Bowling Green", "Owensboro", "Covington"],
    "LA": ["New Orleans", "Baton Rouge", "Shreveport", "Metairie", "Lafayette",
            "Lake Charles", "Kenner", "Bossier City", "Monroe"],
    "ME": ["Portland", "Lewiston", "Bangor", "South Portland", "Augusta"],
    "MD": ["Baltimore", "Rockville", "Frederick", "Gaithersburg", "Bowie",
            "Hagerstown", "Annapolis", "College Park", "Bethesda", "Silver Spring"],
    "MA": ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell",
            "Brockton", "New Bedford", "Quincy", "Lynn", "Newton"],
    "MI": ["Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Lansing",
            "Ann Arbor", "Flint", "Dearborn", "Livonia", "Troy"],
    "MN": ["Minneapolis", "Saint Paul", "Rochester", "Duluth", "Bloomington",
            "Brooklyn Park", "Plymouth", "Maple Grove", "Woodbury", "Edina"],
    "MS": ["Jackson", "Gulfport", "Southaven", "Hattiesburg", "Biloxi"],
    "MO": ["Kansas City", "Saint Louis", "Springfield", "Columbia", "Independence",
            "Lee's Summit", "O'Fallon", "St. Joseph", "St. Charles"],
    "MT": ["Billings", "Missoula", "Great Falls", "Bozeman", "Butte"],
    "NE": ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney"],
    "NV": ["Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks",
            "Carson City", "Summerlin", "Paradise"],
    "NH": ["Manchester", "Nashua", "Concord", "Derry", "Dover"],
    "NJ": ["Newark", "Jersey City", "Paterson", "Elizabeth", "Trenton",
            "Camden", "Clifton", "Passaic", "Hoboken", "Bayonne"],
    "NM": ["Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe", "Roswell"],
    "NY": ["New York City", "Buffalo", "Rochester", "Yonkers", "Syracuse",
            "Albany", "New Rochelle", "Mount Vernon", "Schenectady", "Utica",
            "Manhattan", "Brooklyn", "Queens", "Bronx", "Staten Island"],
    "NC": ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem",
            "Fayetteville", "Cary", "Wilmington", "High Point", "Concord"],
    "ND": ["Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo"],
    "OH": ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron",
            "Dayton", "Parma", "Canton", "Youngstown", "Lorain"],
    "OK": ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Lawton",
            "Edmond", "Moore", "Midwest City", "Stillwater"],
    "OR": ["Portland", "Salem", "Eugene", "Gresham", "Hillsboro",
            "Bend", "Beaverton", "Medford", "Springfield", "Corvallis"],
    "PA": ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading",
            "Scranton", "Bethlehem", "Lancaster", "Harrisburg", "York"],
    "RI": ["Providence", "Cranston", "Warwick", "Pawtucket", "East Providence"],
    "SC": ["Columbia", "Charleston", "North Charleston", "Mount Pleasant", "Rock Hill",
            "Greenville", "Summerville", "Goose Creek", "Myrtle Beach"],
    "SD": ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Watertown"],
    "TN": ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville",
            "Murfreesboro", "Franklin", "Jackson", "Johnson City", "Brentwood"],
    "TX": ["Houston", "San Antonio", "Dallas", "Austin", "Fort Worth",
            "El Paso", "Arlington", "Corpus Christi", "Plano", "Laredo",
            "Lubbock", "Garland", "Irving", "Amarillo", "Frisco",
            "McKinney", "Brownsville", "Killeen", "Midland", "Odessa"],
    "UT": ["Salt Lake City", "West Valley City", "Provo", "West Jordan", "Orem",
            "Sandy", "Ogden", "St. George", "Layton", "South Jordan"],
    "VT": ["Burlington", "South Burlington", "Rutland", "Barre", "Montpelier"],
    "VA": ["Virginia Beach", "Norfolk", "Chesapeake", "Richmond", "Newport News",
            "Alexandria", "Hampton", "Roanoke", "Portsmouth", "Suffolk"],
    "WA": ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue",
            "Kent", "Everett", "Renton", "Yakima", "Kirkland"],
    "WV": ["Charleston", "Huntington", "Morgantown", "Parkersburg", "Wheeling"],
    "WI": ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine",
            "Appleton", "Waukesha", "Oshkosh", "Eau Claire", "Janesville"],
    "WY": ["Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs"],
}
